language: swift
osx_image: Xcode 10.1

xcode_project: release-it.xcodeproj # path to your xcodeproj folder
xcode_scheme: release-itTests
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X

script:
- xctool clean build -workspace XLProjectName.xcworkspace -scheme XLProjectName -sdk iphonesimulator | xcpretty
- xcodebuild test -workspace XLProjectName.xcworkspace -scheme XLProjectName -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=9.3' | xcpretty
